### ISSUE TITLE
decodePolyline fails for some encoded polylines

### ISSUE THREAD

**Issue by BoHellgren** [Dammyololade/flutter_polyline_points#31]
decodePolyline works with this argument:
```
"clgiJchkmBi@QKgCF}@kBCPcG}B]L_IN[G{AD{@l@kAE}@NiA{@`Cq@~@iBpBKjL}Bx@PzBkCrLcBiDn@_BoBoD_CoEcAvAoCcLZc@[cBrAiBu@p@[{Ar@}AqAuGf@u@rDkBe@v@d@xCzCuEvA_CtBcDbD_Hh@jAgA|HyAtEsBtIgBrQ_DmEcAmDsC}K{CaYwAlAVpA"
```
but fails with this argument:

```
"_lgiJ_hkmBs@eEiB_@NsF`CR?qAeAUdALR{LyF|Bz@kJ_AnCkDnDi@lLoA\T~BqCbMwAeEb@qAoFaK}@bBgDiOlBoCs@~@a@kB|A{B`C`J|CjElCaUvFmWgAwAwIfQ{CjFe@iCb@{@}EtBkAuN{Aj@i@oDJD"
```

Both made with the [Interactive Polyline Encoder Utility](https://developers.google.com/maps/documentation/utilities/polylineutility)

The second case results in these error messages:

```
E/flutter (22218): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..154: 155
E/flutter (22218): #0      String.codeUnitAt (dart:core-patch/string_patch.dart:962:55)
E/flutter (22218): #1      NetworkUtil.decodeEncodedPolyline (package:flutter_polyline_points/src/network_util.dart:87:21)
E/flutter (22218): #2      PolylinePoints.decodePolyline (package:flutter_polyline_points/flutter_polyline_points.dart:47:17)
E/flutter (22218): #3      _MyHomePageState.initMap (package:ndskonst/main.dart:162:29)
```

**Comment by BoHellgren** [comment]
I can decode the second string with the utility, but not with my Flutter code. Could it be the back-slash in the second string that causes the problem?

**Comment by BoHellgren** [comment]
Prepending the second string with an 'r', making it a raw string, solved the problem!
