### ISSUE TITLE
RangeError (index): Invalid value: Not in range 0..254

### ISSUE THREAD

**Issue by parhampb** [Dammyololade/flutter_polyline_points#7]
We are getting this error while decoding a polyline.

Encoded polyline:
`xyrbEohoaUeMhDyA^i@TWk@q@gDq@cD?eCFgI?wBdAANGPAlMEtEGMmB?iCF[AiCAeK?yEI]AY?o@Ay@AiCA_F?}BBO?UAm@?}@CaFKs]GkTAaDEYAuACoCGkBMaCGsAAqAAmA?mH?uG?cPCcGCaBKcBW}BOcAqAuHo@uCg@yBc@uDSeCgA}PaCq]iAgQgBkWsAgS_@oFi@aKE}DE{JCyQEyFA{KGsVKwc@AwN?}HAyDBqFJuPHoXDaOTeKRwFJ`

Stacktrace: (from the library call onwards)
`[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..254, inclusive: 255
#0      String.codeUnitAt (dart:core-patch/string_patch.dart:961:55)
#1      NetworkUtil.decodeEncodedPolyline (package:flutter_polyline_points/src/network_util.dart:59:21)
#2      PolylinePoints.decodePolyline (package:flutter_polyline_points/flutter_polyline_points.dart:30:17)`

This polyline does decode when you put it in the Google Polyline decoder:
https://developers.google.com/maps/documentation/utilities/polylineutility

**Comment by parhampb** [comment]
After some further debugging I have realised that the issue was with the encoded string and not the library
The Google utility seems to just stop processing after it hits an "error" and just show what it could decode
For reference, the issue with the string above is that it was capped at 255 characters (api response)
